### ISSUE TITLE
The page link of our Disqus (our comment plugin) admin portal is wrong

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website#193]
I don't know why the URL contains two slashes "//" here. It makes the link unable to render the comment area.

![image](https://user-images.githubusercontent.com/3787410/112408225-6702bf00-8d52-11eb-92df-99a88a3878d1.png)

**Comment by hsluoyz** [comment]
@Oyyko

**Comment by Oyyko** [comment]
Hi. I was wondering if I have to have the admin username and password in disqus to see this bug. Because when I log in use my own disqus account, the website [casbin.disqus.com](url) cannot be visited.

**Comment by Oyyko** [comment]
It seems that [Here](https://github.com/crystal-lang/crystal-website/issues/62) is the same question. However I still cannot find a good way to solve it. I was wondering if I can update the real casbin website so that I can test my ideas. Now, my solutions was to change the website url in /website/siteConfig.js and see what will happen. Maybe it can fix the issue but we will lose all past comment, maybe not.

**Comment by hsluoyz** [comment]
@Oyyko we can send an issue about it to the Disqus official team: https://github.com/disqus/disqus-react/issues

**Comment by hsluoyz** [comment]
The issue is here: https://github.com/disqus/disqus-react/issues/93

@ErikQQY plz follow up.

**Comment by ErikQQY** [comment]
Following these threads

**Comment by ErikQQY** [comment]
@hsluoyz This issue is now solved, I think there are no wrong comment links in our Disqus admin portal.

**Comment by hsluoyz** [comment]
@ErikQQY I saw it: https://github.com/disqus/disqus-react/issues/93#issuecomment-886348416 thanks!
