### ISSUE TITLE
Languages are contrained to very few languages 

### ISSUE THREAD

**Issue by Cronus1007** [casbin/casbin-website#197]
## Problem Description 
The langugaes.js has been contrained to very few languages i.e. Eng,Russian etc. This can be extended into several other languages.

## Solution 
Extending languages.js to include several other languages like Portuguese etc.

@hsluoyz Any opinion about this?

**Comment by hsluoyz** [comment]
@Cronus1007 we don't add a lot of languages to the drop-down menu because there's no translators for it. I don't want to have 100 languages listed there but only English and Chinese have useful stuff in it, other 98 languages are empty shells.

Are you willing to translate a language? If yes, I can open up that language for you.

**Comment by Cronus1007** [comment]
@hsluoyz Sure.I would love to do it.

**Comment by Cronus1007** [comment]
@hsluoyz Sure.
